%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#eef9f0', 'primaryTextColor': '#163b21', 'primaryBorderColor': '#2d6a3a', 'lineColor': '#2d6a3a', 'fontFamily': 'Arial' }}}%%
flowchart TB
    T[Gobierno y Control de Acceso]
    T --> C[Comite Institucional]
    C --> CF[Comite Funcional]
    C --> CT[Comite Tecnico]
    CF --> P1[Priorizacion de requerimientos]
    CT --> P2[Validacion de arquitectura y seguridad]

    P1 --> U1[Rol Consulta]
    P1 --> U2[Rol Editor]
    P2 --> U3[Rol Administrador]

    U1 --> D1[Modulo Archivo]
    U1 --> D2[Modulo RRHH]
    U2 --> D1
    U2 --> D2
    U3 --> D3[Administracion y Gobierno]

    D1 --> LOG[Auditoria de eventos]
    D2 --> LOG
    D3 --> LOG
